providers  = ["node"]
buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu"

[variables]
NIXPACKS_DEBIAN       = "true"
CI                     = "true"
NODE_ENV               = "production"
NIXPACKS_NODE_VERSION  = "22.17.0"
NIXPACKS_METADATA      = "node"
NPM_CONFIG_PRODUCTION  = "false"
TARGET_ENV             = "production"

[phases.setup]
nixPkgs = [
  "...",              # preserve the Node provider’s own snapshot
  "nodejs_22",        # Node 22
  "python311Full",    # if you need to run any Python script at build time
  "gcc",              # so that node-gyp can compile native code
  "binutils",         # linker, etc.
  "pkg-config",       # pkg-config itself
  "git",
  "libusb1.dev",      # drops libusb-1.0 headers + .so
  "systemd.dev"       # drops libudev headers + .so
]

# You’ll get both headers and the .pc files under ~/.nix-profile/lib/pkgconfig
nixLibs = [
  "...",
  "libusb1.dev",
  "systemd.dev"
]

# You do not strictly need libusb-1.0-0-dev or libudev-dev from apt
# because Nix’s libusb1.dev + systemd.dev supply those headers.
aptPkgs = [
  "curl",
  "wget"
]

# Just sanity‐check where libudev.h ended up:
cmds = [
  "echo '→ Checking for libudev.h in /nix/store…'; find /nix -type f -name libudev.h",
  "echo '→ Checking for libusb-1.0.pc in /nix'; find /nix -type f -name libusb-1.0.pc",
  "echo '→ Checking for libudev.pc in /nix'; find /nix -type f -name libudev.pc"
  
]

# ───────────────────────────────────────────────────────────────────────────────
[phases.install.env]
# We’ll let pkg-config provide the right "-I" flags, so we only need:
PYTHON = "python3"
# Point pkg-config at the Nix profile directory where all .pc files live:
PKG_CONFIG_PATH = "/root/.nix-profile/lib/pkgconfig"

[phases.install]
dependsOn = ["setup"]
cmds = ["echo '→ Starting install phase…' && PC_DIRS=\"$(find /nix -type f \\( -name 'libudev.pc' -o -name 'libusb-1.0.pc' \\) -exec dirname {} \\; 2>/dev/null | sort -u | tr '\\n' ':')\" && export PKG_CONFIG_PATH=\"/root/.nix-profile/lib/pkgconfig:${PC_DIRS%:}\" && export CFLAGS=\"$(pkg-config --cflags-only-I libudev libusb-1.0)\" && export LDFLAGS=\"$(pkg-config --libs-only-L libudev libusb-1.0)\" && export LIBRARY_PATH=\"$(pkg-config --libs-only-L libudev libusb-1.0 | sed -e 's/-L//g')\" && echo \"CFLAGS is now → $CFLAGS\" && echo \"LDFLAGS is now → $LDFLAGS\" && echo \"LIBRARY_PATH is now → $LIBRARY_PATH\" && npm install"]


# ───────────────────────────────────────────────────────────────────────────────
[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]
# ───────────────────────────────────────────────────────────────────────────────