name: REWTF Activity Tracker

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Her gün saat 12:00'da çalış (UTC)
    - cron: '0 12 * * *'

jobs:
  track-activity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run lint
      
    - name: Build project
      run: npm run build
      
    - name: REWTF Activity Log
      run: |
        echo "🏆 REWTF Activity Logged!"
        echo "📊 Commit: ${{ github.sha }}"
        echo "👤 Author: ${{ github.actor }}"
        echo "📅 Date: $(date)"
        echo "🌊 Flow Project: FlowSwap"
        echo "📈 Leaderboard: https://app.databox.com/datawall/fc5f1f7de13471eac8bd5eb2e3d90a752817ac68a86fd6"
        
    - name: Comment on PR (if PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🏆 **REWTF Tracker**: Bu PR FlowSwap projesine katkı sağlıyor! #ReWTF #FlowBlockchain'
          })